
export const integrantes = [
    { id: 0, name: 'Amanda', img: 'https://i.pinimg.com/736x/03/d3/86/03d386d8b7da2b2279f8df5b8f065446.jpg', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer' },
    { id: 1, name: 'Ana', img: 'https://i.pinimg.com/550x/ce/e6/3b/cee63b1fc30e57907144ae3f0736725d.jpg', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
    { id: 2, name: 'Daniel', img: 'https://dfg.ai/itemimages/977380375-pack-de-fotos-fake-de-pessoas-inexistentes-E918.jpg', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
    { id: 3, name: 'Gabriel', img: 'https://www.rbsdirect.com.br/imagesrc/24284454.jpg?w=1024&h=1024&a=c', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
    { id: 4, name: 'Layon', img: 'https://www.rbsdirect.com.br/imagesrc/24284454.jpg?w=1024&h=1024&a=c', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
    { id: 5, name: 'Romulo', img: 'https://i.pinimg.com/originals/99/ae/ec/99aeecad5763596a71b5400032704859.jpg', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
    { id: 6, name: 'Yuri', img: 'https://salaovirtual.org/wp-content/uploads/2022/03/cacheado-colorido-pela-metade-3-1.jpg', descricao: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, sequi aperiam. Dolorum libero, quam nostrum, repudiandae minus numquam voluptatibus illo eveniet in ea nam saepe quibusdam exercitationem voluptas facer'  },
]